# receivers:
#   otlp:
#     protocols:
#       grpc:

# exporters:
#   logging:
#     loglevel: debug
#   jaeger:
#     endpoint: "jaeger:14250" # Adjust based on your setup

# service:
#   pipelines:
#     traces:
#       receivers: [otlp]
#       exporters: [logging, jaeger]